# Generated by Django 3.1.2 on 2020-10-01 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ghostpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghostpost_choice', models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], max_length=1)),
                ('ghostpost_content', models.CharField(max_length=280, verbose_name='Content')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
