# Generated by Django 3.1.2 on 2020-10-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='ghostpost_choice',
            field=models.CharField(blank=True, choices=[('B', 'Boast'), ('R', 'Roast')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='ghostpost_content',
            field=models.CharField(blank=True, max_length=280, verbose_name='Content'),
        ),
    ]
